[package]
name = "joy"
version = "0.1.0"
authors = ["Kevin Rauwolf <sweetpea-git@tentacle.net>"]

[dependencies]
hyper = "0.9"
serde = "0.7"
serde_json = "0.7"
iron = "0.4"
handlebars = "0.21"
handlebars-iron = "0.18"
logger = "0.1"
error-chain = "0.5"
time = "0.1"
